[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[service]
internalPort = 3000
